name: 'Repo Automator'
on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - edited
      - converted_to_draft
      - ready_for_review
    branches:
      - develop

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: 10up/action-pr-automator@dependabot/npm_and_yarn/octokit/action-6.0.6
        with:
          fail-label: needs:feedback
          pass-label: needs:code-review
          reviewer: iamdharmesh
          sync-pr-branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
